/*
 * generated by Xtext
 */
package ar.edu.unq.obj3.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TextualVerdulerRuntimeModule extends ar.edu.unq.obj3.dsl.AbstractTextualVerdulerRuntimeModule {

}
