/*
 * generated by Xtext
 */
package ar.edu.unq.obj3.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TextualVerdulerStandaloneSetup extends TextualVerdulerStandaloneSetupGenerated{

	public static void doSetup() {
		new TextualVerdulerStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

