/*
 * generated by Xtext
 */
package ar.edu.unq.obj3.dsl.ui.contentassist

import ar.edu.unq.obj3.dsl.ui.contentassist.AbstractTextualVerdulerProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TextualVerdulerProposalProvider extends AbstractTextualVerdulerProposalProvider {
}
