-- MySQL Script generated by MySQL Workbench
-- 07/12/15 01:39:47
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema verduleria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `verduleria` DEFAULT CHARACTER SET utf8 ;
USE `verduleria` ;

-- -----------------------------------------------------
-- Table `verduleria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verduleria`.`cliente` (
  `NOMBRE` VARCHAR(20) NOT NULL,
  `SALDO`  DOUBLE NOT NULL,
  PRIMARY KEY (`NOMBRE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verduleria`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verduleria`.`compra` (
  `ID_COMPRA` INT(11) NOT NULL AUTO_INCREMENT,
  `COMPRADOR` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_COMPRA`),
  INDEX `fk_compras_clientes_idx` (`COMPRADOR` ASC),
  CONSTRAINT `fk_compras_clientes`
    FOREIGN KEY (`COMPRADOR`)
    REFERENCES `verduleria`.`cliente` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verduleria`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verduleria`.`producto` (
  `NOMBRE` VARCHAR(20) NOT NULL,
  `PRECIO` INT(11) NOT NULL,
  `KILOS` DOUBLE NOT NULL,
  PRIMARY KEY (`NOMBRE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verduleria`.`producto_comprado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verduleria`.`producto_comprado` (
  `ID_COMPRA` INT(11) NULL DEFAULT NULL,
  `ID_PRODUCTO` VARCHAR(20) NULL DEFAULT NULL,
  `KILOS` DOUBLE NULL DEFAULT NULL,
  INDEX `fk_producto_comprado_compra1_idx` (`ID_COMPRA` ASC),
  INDEX `fk_producto_comprado_producto1_idx` (`ID_PRODUCTO` ASC),
  CONSTRAINT `id_compra_fk`
    FOREIGN KEY (`ID_COMPRA`)
    REFERENCES `verduleria`.`compra` (`ID_COMPRA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_producto_fk`
    FOREIGN KEY (`ID_PRODUCTO`)
    REFERENCES `verduleria`.`producto` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
