/*
 * generated by Xtext
 */
package ar.edu.unq.obj3.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TextualVerdulerUiModule extends ar.edu.unq.obj3.dsl.ui.AbstractTextualVerdulerUiModule {
	public TextualVerdulerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
